# Generated by Django 3.0.3 on 2020-07-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usersignuptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=30)),
            ],
        ),
    ]
